// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: getCaptcha.proto

package getCaptcha

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 生成验证码直接由框架完成 不用传入参数
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getCaptcha_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_getCaptcha_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_getCaptcha_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 穿出参数是图片 不过图片嵌套了多层结构体不好表示 可以将图片作为字节数传给客户端，客户端再反序列化为图片对象
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 字节切片存储图片信息 json序列化
	Img []byte `protobuf:"bytes,1,opt,name=img,proto3" json:"img,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getCaptcha_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_getCaptcha_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_getCaptcha_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetImg() []byte {
	if x != nil {
		return x.Img
	}
	return nil
}

var File_getCaptcha_proto protoreflect.FileDescriptor

var file_getCaptcha_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x67, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x22, 0x1d,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x1c, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6d, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x32, 0x41, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x12, 0x33, 0x0a, 0x04, 0x43, 0x61, 0x6c,
	0x6c, 0x12, 0x13, 0x2e, 0x67, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74,
	0x63, 0x68, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a,
	0x5a, 0x18, 0x2e, 0x2e, 0x2f, 0x67, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x3b,
	0x67, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_getCaptcha_proto_rawDescOnce sync.Once
	file_getCaptcha_proto_rawDescData = file_getCaptcha_proto_rawDesc
)

func file_getCaptcha_proto_rawDescGZIP() []byte {
	file_getCaptcha_proto_rawDescOnce.Do(func() {
		file_getCaptcha_proto_rawDescData = protoimpl.X.CompressGZIP(file_getCaptcha_proto_rawDescData)
	})
	return file_getCaptcha_proto_rawDescData
}

var file_getCaptcha_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getCaptcha_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: getCaptcha.Request
	(*Response)(nil), // 1: getCaptcha.Response
}
var file_getCaptcha_proto_depIdxs = []int32{
	0, // 0: getCaptcha.GetCaptcha.Call:input_type -> getCaptcha.Request
	1, // 1: getCaptcha.GetCaptcha.Call:output_type -> getCaptcha.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getCaptcha_proto_init() }
func file_getCaptcha_proto_init() {
	if File_getCaptcha_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getCaptcha_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getCaptcha_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getCaptcha_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getCaptcha_proto_goTypes,
		DependencyIndexes: file_getCaptcha_proto_depIdxs,
		MessageInfos:      file_getCaptcha_proto_msgTypes,
	}.Build()
	File_getCaptcha_proto = out.File
	file_getCaptcha_proto_rawDesc = nil
	file_getCaptcha_proto_goTypes = nil
	file_getCaptcha_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetCaptchaClient is the client API for GetCaptcha service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetCaptchaClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getCaptchaClient struct {
	cc grpc.ClientConnInterface
}

func NewGetCaptchaClient(cc grpc.ClientConnInterface) GetCaptchaClient {
	return &getCaptchaClient{cc}
}

func (c *getCaptchaClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/getCaptcha.GetCaptcha/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCaptchaServer is the server API for GetCaptcha service.
type GetCaptchaServer interface {
	Call(context.Context, *Request) (*Response, error)
}

// UnimplementedGetCaptchaServer can be embedded to have forward compatible implementations.
type UnimplementedGetCaptchaServer struct {
}

func (*UnimplementedGetCaptchaServer) Call(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}

func RegisterGetCaptchaServer(s *grpc.Server, srv GetCaptchaServer) {
	s.RegisterService(&_GetCaptcha_serviceDesc, srv)
}

func _GetCaptcha_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetCaptchaServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/getCaptcha.GetCaptcha/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetCaptchaServer).Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetCaptcha_serviceDesc = grpc.ServiceDesc{
	ServiceName: "getCaptcha.GetCaptcha",
	HandlerType: (*GetCaptchaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _GetCaptcha_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getCaptcha.proto",
}
