# 微服务配置
server:
  domain: Order
  version: 1.0
  jwtSecret: 38324
#  grpcAddress: "order_srv:3004" #不同微服务记得修改端口号
  grpcAddress: "127.0.0.1:3004" #不同微服务记得修改端口号

etcd:
#  address: "etcd-server:2379"
  address: "127.0.0.1:2379"

captcha:
  # 验证码字符数
  num: 4
  # 验证码字符类型 0是纯数字类型
  strType: 0

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 50
  max_conn_age: 300 #second
  idle_timeout: 60 #second

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "root"
  database: "bj38web"
  charset: "utf8mb4"
  max_open_conns: 100
  max_idle_conns: 50