// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "author：@ouzhsh",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1.0/areas": {
            "get": {
                "description": "获取地域信息Description",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户业务接口Tags"
                ],
                "summary": "获取地域信息Summary",
                "parameters": [
                    {
                        "description": "手机号",
                        "name": "mobile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "地域",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/house/index": {
            "get": {
                "description": "获取首页轮播图片服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "获取首页轮播图片服务"
                ],
                "summary": "获取首页轮播图片服务",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/houses": {
            "get": {
                "description": "搜索房屋",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "搜索房"
                ],
                "summary": "搜索房屋",
                "parameters": [
                    {
                        "type": "string",
                        "description": "areaId",
                        "name": "aid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "start day",
                        "name": "sd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "end day",
                        "name": "ed",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "排序方式",
                        "name": "sk",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "发布房屋信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发布房屋信息"
                ],
                "summary": "发布房屋信息",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "userName",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "房屋信息",
                        "name": "HouseStu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.HouseStu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/houses/:id": {
            "get": {
                "description": "展示房屋详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "展示房屋详情"
                ],
                "summary": "展示房屋详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "房屋号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/houses/:id/images": {
            "post": {
                "description": "上传房屋图片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "上传房屋图片"
                ],
                "summary": "上传房屋图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图片号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/imagecode/:uuid": {
            "get": {
                "description": "获取图片验证码",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "用户业务接口"
                ],
                "summary": "图片验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径变量参数",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "验证码",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/orders": {
            "post": {
                "description": "下订单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下订单"
                ],
                "summary": "下订单",
                "parameters": [
                    {
                        "description": "图片号",
                        "name": "ordert",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/orders/:id/comment": {
            "put": {
                "description": "订单评价",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单评价"
                ],
                "summary": "订单评价",
                "parameters": [
                    {
                        "description": "Comment",
                        "name": "Comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.Comment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/orders/:id/status": {
            "put": {
                "description": "更新订单状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "更新订单状态"
                ],
                "summary": "更新订单状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/session": {
            "get": {
                "description": "获取session信息服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户业务接口"
                ],
                "summary": "用户会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "查询参数",
                        "name": "object",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户名",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "退出登录状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户业务接口"
                ],
                "summary": "退出登录状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "查询参数",
                        "name": "object",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "消息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/sessions": {
            "post": {
                "description": "用户登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户业务接口"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "手机号",
                        "name": "mobile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "密码",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "消息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/smscode/:mobile": {
            "get": {
                "description": "获取短信验证码",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户业务接口"
                ],
                "summary": "短信验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径变量参数",
                        "name": "phone",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "消息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/user": {
            "get": {
                "description": "获取用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户业务接口"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/user/auth": {
            "post": {
                "description": "用户实名认证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户实名认证"
                ],
                "summary": "用户实名认证",
                "parameters": [
                    {
                        "description": "真实姓名",
                        "name": "real_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "身份证",
                        "name": "id_card",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/user/avatar": {
            "post": {
                "description": "上传用户头像",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "上传用户头像"
                ],
                "summary": "上传用户头像",
                "parameters": [
                    {
                        "type": "file",
                        "description": "用户名",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/user/houses": {
            "get": {
                "description": "获取用户发布的房源信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "获取用户发布的房源信息"
                ],
                "summary": "获取用户发布的房源信息",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "userName",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/user/name": {
            "put": {
                "description": "修改用户名提交",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "修改用户名提交"
                ],
                "summary": "修改用户名提交",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/user/orders": {
            "get": {
                "description": "获取订单信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "获取订单信息"
                ],
                "summary": "获取订单信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "role",
                        "name": "role",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1.0/users": {
            "post": {
                "description": "提交用户注册请求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户业务接口"
                ],
                "summary": "提交用户注册请求",
                "parameters": [
                    {
                        "description": "手机号",
                        "name": "mobile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "密码",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "验证码",
                        "name": "sms_code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "消息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Comment": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                }
            }
        },
        "controller.HouseStu": {
            "type": "object",
            "properties": {
                "acreage": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "area_id": {
                    "type": "string"
                },
                "beds": {
                    "type": "string"
                },
                "capacity": {
                    "type": "string"
                },
                "deposit": {
                    "type": "string"
                },
                "facility": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "max_days": {
                    "type": "string"
                },
                "min_days": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "room_count": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "127.0.0.1:8080",
	BasePath:         "/api/v1.0",
	Schemes:          []string{},
	Title:            "bj38web",
	Description:      "Go Web bj38web",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	//LeftDelim:        "{{",
	//RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
