// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: getArea.proto

package getArea

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 地域信息请求消息
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getArea_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_getArea_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_getArea_proto_rawDescGZIP(), []int{0}
}

// 地域信息响应消息
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 微服务返回的错误码和消息响应
	Errno  string `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Area   string `protobuf:"bytes,3,opt,name=area,proto3" json:"area,omitempty"` //地域信息json字符串
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getArea_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_getArea_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_getArea_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetErrno() string {
	if x != nil {
		return x.Errno
	}
	return ""
}

func (x *Response) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *Response) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

var File_getArea_proto protoreflect.FileDescriptor

var file_getArea_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x67, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x22, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65,
	0x61, 0x32, 0x3e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x12, 0x33, 0x0a, 0x0c,
	0x4d, 0x69, 0x63, 0x72, 0x6f, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x12, 0x10, 0x2e, 0x67,
	0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x67, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2e, 0x2f, 0x67, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x3b,
	0x67, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_getArea_proto_rawDescOnce sync.Once
	file_getArea_proto_rawDescData = file_getArea_proto_rawDesc
)

func file_getArea_proto_rawDescGZIP() []byte {
	file_getArea_proto_rawDescOnce.Do(func() {
		file_getArea_proto_rawDescData = protoimpl.X.CompressGZIP(file_getArea_proto_rawDescData)
	})
	return file_getArea_proto_rawDescData
}

var file_getArea_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getArea_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: getArea.Request
	(*Response)(nil), // 1: getArea.Response
}
var file_getArea_proto_depIdxs = []int32{
	0, // 0: getArea.GetArea.MicroGetArea:input_type -> getArea.Request
	1, // 1: getArea.GetArea.MicroGetArea:output_type -> getArea.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getArea_proto_init() }
func file_getArea_proto_init() {
	if File_getArea_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getArea_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getArea_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getArea_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getArea_proto_goTypes,
		DependencyIndexes: file_getArea_proto_depIdxs,
		MessageInfos:      file_getArea_proto_msgTypes,
	}.Build()
	File_getArea_proto = out.File
	file_getArea_proto_rawDesc = nil
	file_getArea_proto_goTypes = nil
	file_getArea_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetAreaClient is the client API for GetArea service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetAreaClient interface {
	MicroGetArea(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getAreaClient struct {
	cc grpc.ClientConnInterface
}

func NewGetAreaClient(cc grpc.ClientConnInterface) GetAreaClient {
	return &getAreaClient{cc}
}

func (c *getAreaClient) MicroGetArea(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/getArea.GetArea/MicroGetArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAreaServer is the server API for GetArea service.
type GetAreaServer interface {
	MicroGetArea(context.Context, *Request) (*Response, error)
}

// UnimplementedGetAreaServer can be embedded to have forward compatible implementations.
type UnimplementedGetAreaServer struct {
}

func (*UnimplementedGetAreaServer) MicroGetArea(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MicroGetArea not implemented")
}

func RegisterGetAreaServer(s *grpc.Server, srv GetAreaServer) {
	s.RegisterService(&_GetArea_serviceDesc, srv)
}

func _GetArea_MicroGetArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetAreaServer).MicroGetArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/getArea.GetArea/MicroGetArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetAreaServer).MicroGetArea(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetArea_serviceDesc = grpc.ServiceDesc{
	ServiceName: "getArea.GetArea",
	HandlerType: (*GetAreaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MicroGetArea",
			Handler:    _GetArea_MicroGetArea_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getArea.proto",
}
